name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/Login-action@v3     
        with: 
          username: ${{ secrets.amukiran}}
          password: ${{ secrets.Devops$1289$}}
    
      - name: Build Docker Image
        run: docker build -t amukiran/mysite:latest .

      - name: Push Docker Image    
        run: docker push amukiran/mysite:latest  
